version: '3'
services:
    ws:
        image: "clalanne/goexperiment"
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true

    db:
        image: "clalanne/goexperiment_db"
        environment:
            - MYSQL_DATABASE=cdr
            - MYSQL_ROOT_PASSWORD=pass
        ports:
            - "3306:3306"
        stdin_open: true
        tty: true

