version: '3'
services:
    ws:
        image: "clalanne/goexperiment"
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true

    http:
        image: "clalanne/goexperiment_http"
        ports:
            - "8080:8080"
        stdin_open: true
        tty: true

    tests:
        image: "clalanne/goexperiment_tests"

    db:
        image: "clalanne/goexperiment_db"
        environment:
            - MYSQL_ROOT_PASSWORD=pass
        ports:
            - "3306:3306"
        stdin_open: true
        tty: true

